language: python
python:
    - "2.7"
before_install:
 - sudo apt-get update -qq
install:
    - pip install pelican==3.6.3 Markdown==2.6.7 beautifulsoup4==4.5.1
script:
    - rm -rf ./output
    - rm -rf ./cache
    - rm -rf ./plugins/*
    - git clone https://github.com/getpelican/pelican-plugins.git
    - mv ./pelican-plugins/* ./plugins
    - pelican ./content -o ./output -s ./publishconf.py
    - git clone --quiet https://${GH_TOKEN}@github.com/johnpfeiffer/johnpfeiffer.github.io.git > /dev/null
    - cd johnpfeiffer.github.io
    - git config user.email "me@john-pfeiffer.com"
    - git config user.name "John Pfeiffer"
    - rsync -rv --exclude=.git ../output/* .
    - git add -f .
    - git commit -m "Travis build $TRAVIS_BUILD_NUMBER"
    - git push -fq origin master > /dev/null
    - echo -e "Done\n"
env:
  global:
    secure: cex4RgZNUpLwCF40sZTBj7/m+aINEzKi5qMBMIyjLHKfnETmjpzSGPVf+P3qjNgpUvV2TaSHFScVqNMEfeUY6fUjPLw6XIQayOYvBNjPEpmjeqNbnGu/SC31dDYazOPWyIWrQ26IP
B8v6JkhcbVJBpuiaZqvynEL8F2CoRsTAEA=

