language: python
python:
    - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends ruby-sass
install:
    - pip install -vv -r requirements.txt
script:
    - pelican --help
