[project]
name = "pelicansite"
version = "0.1.0"
description = "John Pfeiffer blog"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pelican[markdown]>=4.11.0",
    "beautifulsoup4 >=4.14",
]

[project.optional-dependencies]
markdown = [
    "pelican>=4.11.0",
]

