version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Pelican and Build Content
          command: |
            python -m pip install "pelican[markdown]" beautifulsoup4
            pip freeze | grep pelican
            cd ..
            pwd
            ls -ahl /home/circleci/project
            find . -type f -iname pelican
            cd .pyenv/versions/3.8.11/bin/
            ./pelican --version
            ./pelican /home/circleci/project/content -o /home/circleci/project/output -s /home/circleci/project/publishconf.py
            ls -ahl /home/circleci/.ssh/

      - add_ssh_keys:
                  fingerprints:
                              - "4e:c1:a6:83:cc:89:e6:89:ed:53:a3:f4:46:9b:d8:d7"
      - run:
          name: Publish to GitHub Static Site
          command: |
            cd ..
            ls -ahl
            git clone git@github.com:johnpfeiffer/johnpfeiffer.github.io.git
            cd johnpfeiffer.github.io
            git config user.email "me@john-pfeiffer.com"
            git config user.name "John Pfeiffer CircleCI"
            git checkout master
            cp -a /home/circleci/project/output/* .
            git commit --allow-empty -am "CircleCI publishing $CIRCLE_BUILD_NUM from sha $CIRCLE_SHA1"
            ls -ahl ~/.ssh/
            GIT_SSH_COMMAND='ssh -v -i ~/.ssh/id_rsa_4e:c1:a6:83:cc:89:e6:89:ed:53:a3:f4:46:9b:d8:d7' git push origin master'

