version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Pelican
          command: |
            python -m pip install "pelican[markdown]" beautifulsoup4
            pip freeze | grep pelican
            cd ..
            pwd
            ls -ahl /home/circleci/project
            find . -type f -iname pelican
            cd .pyenv/versions/3.8.11/bin/
            ./pelican --version
            ./pelican /home/circleci/project/content -o /home/circleci/project/output -s ./publishconf.py
