version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Pelican
          command: |
            python -m pip install "pelican[markdown]" 
            ls -ahl
            pip freeze | grep pelican
            cd ..
            ls -ahl
            find . -type f -iname pelican
            pelican --version
            # which pelican
            # ls -ahl
            # pelican ./content -o ./output -s ./publishconf.py
