version: 2.1
jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install Pelican
          command: |
            python -m pip install "pelican[markdown]" 
            git clone https://github.com/getpelican/pelican-plugins
            pwd
            ls -ahl
            # mv ./pelican-plugins/* ./plugins
            pelican ./content -o ./output -s ./publishconf.py
